services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ContaoThemeManager\Tabs\:
      resource: '../src/'
      exclude: '../src/{Model,DependencyInjection,Resources}'